{"error": null, "issues": [{"address": 314, "code": "msg.sender.call.value(userBalance[msg.sender])()", "debug": "SOLVER OUTPUT:\ncalldata_Reentrance_0: 0x5fd8c71000000000000000000000000000000000000000000000000000000000\ncalldatasize_Reentrance: 0x4\ncallvalue: 0x0\n", "description": "In the function `withdrawBalance()` a non-zero amount of Ether is sent to msg.sender.\nIt seems that this function can be called without restrictions.", "filename": "/dataset/reentrancy/reentrancy_simple.sol", "function": "withdrawBalance()", "lineno": 24, "title": "Ether send", "type": "Warning"}, {"address": 314, "code": "msg.sender.call.value(userBalance[msg.sender])()", "debug": "", "description": "This contract executes a message call to the address of the transaction sender. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/dataset/reentrancy/reentrancy_simple.sol", "function": "withdrawBalance()", "lineno": 24, "title": "Message call to external contract", "type": "Warning"}, {"address": 396, "code": "userBalance[msg.sender] = 0", "debug": "", "description": "The contract account state is changed after an external call. Consider that the called contract could re-enter the function before this state change takes place. This can lead to business logic vulnerabilities.", "filename": "/dataset/reentrancy/reentrancy_simple.sol", "function": "withdrawBalance()", "lineno": 27, "title": "State change after external call", "type": "Warning"}, {"address": 468, "code": "userBalance[msg.sender] += msg.value", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncallvalue: 0x57f25cd000000000000000000000000000000000000000000000000000000000\ncalldata_Reentrance_0: 0xc0e317fb00000000000000000000000000000000000000000000000000000000\ncalldatasize_Reentrance: 0x4\n", "description": "A possible integer overflow exists in the function `addToBalance()`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/dataset/reentrancy/reentrancy_simple.sol", "function": "addToBalance()", "lineno": 17, "title": "Integer Overflow ", "type": "Warning"}], "success": true}