incomplete push instruction at 41
INFO:symExec:	============ Results ===========
Traceback (most recent call last):
  File "/oyente/oyente/oyente.py", line 232, in <module>
    main()
  File "/oyente/oyente/oyente.py", line 221, in main
    exit_code = analyze_bytecode()
  File "/oyente/oyente/oyente.py", line 73, in analyze_bytecode
    result, exit_code = symExec.run(disasm_file=inp['disasm_file'])
  File "/oyente/oyente/symExec.py", line 2458, in run
    analyze()
  File "/oyente/oyente/symExec.py", line 2441, in analyze
    run_build_cfg_and_analyze(timeout_cb=timeout_cb)
  File "/oyente/oyente/symExec.py", line 2398, in run_build_cfg_and_analyze
    build_cfg_and_analyze()
  File "/oyente/oyente/symExec.py", line 228, in build_cfg_and_analyze
    full_sym_exec()  # jump targets are constructed on the fly
  File "/oyente/oyente/symExec.py", line 547, in full_sym_exec
    return sym_exec_block(params, 0, 0, 0, -1, 'fallback')
  File "/oyente/oyente/symExec.py", line 612, in sym_exec_block
    sym_exec_ins(params, block, instr, func_call, current_func_name)
  File "/oyente/oyente/symExec.py", line 1858, in sym_exec_ins
    stack.pop(0)
IndexError: pop from empty list