INFO:root:Contract /dataset/bad_randomness/etheraffle.sol:Ethraffle_v4b:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 421, in propagate_taint
    if arithmetic_error["instruction"].data_in[1] == 32 or arithmetic_error["instruction"].data_in[1] == 31:
  File "/root/osiris/z3/z3.py", line 844, in __eq__
    a, b = _coerce_exprs(self, other)
  File "/root/osiris/z3/z3.py", line 1012, in _coerce_exprs
    b = s.cast(b)
  File "/root/osiris/z3/z3.py", line 3059, in cast
    return BitVecVal(val, self)
  File "/root/osiris/z3/z3.py", line 3596, in BitVecVal
    return BitVecNumRef(Z3_mk_numeral(ctx.ref(), _to_int_str(val), bv.ast), ctx)
  File "/root/osiris/z3/z3.py", line 280, in __init__
    Z3_inc_ref(self.ctx.ref(), self.as_ast())
  File "/root/osiris/z3/z3core.py", line 1369, in Z3_inc_ref
    _elems.Check(a0)
  File "/root/osiris/z3/z3core.py", line 1326, in Check
    err = self.get_error_code(ctx)
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 33.4%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 True
/dataset/bad_randomness/etheraffle.sol:Ethraffle_v4b:111:9
raffleId++
^
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 True
Flow 1:
/dataset/bad_randomness/etheraffle.sol:Ethraffle_v4b:93:13
msg.sender.transfer(moneySent)
^
Flow 2:
/dataset/bad_randomness/etheraffle.sol:Ethraffle_v4b:93:13
msg.sender.transfer(moneySent)
^
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 251.258752108 seconds ---
INFO:symExec:	====== Analysis Completed ======

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
Unexpected error: <type 'exceptions.Exception'>