{
  "contract": "wallet_04_confused_sign",
  "tool": "mythril",
  "start": 1565777010.3027587,
  "end": 1565777016.5374193,
  "duration": 6.234660625457764,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 433,
        "code": "balances[msg.sender] -= amount",
        "debug": "calldata_Wallet_4: 0xfffffffffffffffffffffffffffffffbfffffffffffffffffffffffff0000000\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x1fffffb\nretval_340: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Wallet_0: 0x2e1a7d4d00000000000000000000000000000000000000000000000000000000\ncalldatasize_Wallet: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer underflow exists in the function `withdraw(uint256)`.\nThe subtraction may result in a value < 0.",
        "filename": "/dataset/access_control/wallet_04_confused_sign.sol",
        "function": "withdraw(uint256)",
        "lineno": 32,
        "title": "Integer Underflow",
        "type": "Warning"
      },
      {
        "address": 769,
        "code": "assert(balances[msg.sender] + msg.value > balances[msg.sender])",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncallvalue: 0x0\ncalldata_Wallet_0: 0xd0e30db000000000000000000000000000000000000000000000000000000000\ncalldatasize_Wallet: 0x4\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/dataset/access_control/wallet_04_confused_sign.sol",
        "function": "deposit()",
        "lineno": 24,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}