{"error": null, "issues": [{"address": 196, "code": "count -= input", "debug": "storage_1: 0x0\ncalldata_IntegerOverflowMultiTxOneFuncFeasible_4: 0x1\nstorage_0: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_IntegerOverflowMultiTxOneFuncFeasible_0: 0xa444f5e900000000000000000000000000000000000000000000000000000000\ncalldatasize_IntegerOverflowMultiTxOneFuncFeasible: 0x4\ncallvalue: 0x0\n", "description": "A possible integer underflow exists in the function `run(uint256)`.\nThe subtraction may result in a value < 0.", "filename": "/dataset/arithmetic/integer_overflow_multitx_onefunc_feasible.sol", "function": "run(uint256)", "lineno": 22, "title": "Integer Underflow", "type": "Warning"}], "success": true}